-- MySQL Script generated by MySQL Workbench
-- Wed Jul 17 16:39:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4;
USE `mydb`;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id_Cliente` INT not null,
  `Nome` VARCHAR(100) NULL,
  `Telefone` VARCHAR(15) NULL,
  `Email` VARCHAR(30) NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tema` (
  `idTema` INT not null,
  `Nome` VARCHAR(100) NULL,
  PRIMARY KEY (`idTema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local` (
  `idLocal` INT not null,
  `Nome` VARCHAR(100) NULL,
  `Endereço` VARCHAR(100) NULL,
  PRIMARY KEY (`idLocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bebida` (
  `idBebida` INT not null,
  `Nome` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idBebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comida` (
  `idComida` INT not null,
  `nome` VARCHAR(60) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idComida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT AUTO_INCREMENT,
  `dataEvento` DATETIME NULL,
  `numeroPessoas` INT NULL,
  `status` VARCHAR(20) NULL,
  PRIMARY KEY (`idEvento`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idEvento`)
    REFERENCES `mydb`.`Cliente` (`id_Cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idTema`
    FOREIGN KEY (`idEvento`)
    REFERENCES `mydb`.`Tema` (`idTema`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idLocal`
    FOREIGN KEY (`idEvento`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orcamento` (
  `idOrçamento` INT NOT NULL,
  `dataOrcamento` DATETIME NULL,
  `valorTotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idOrçamento`),
  CONSTRAINT `idEvento`
    FOREIGN KEY (`idOrçamento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orcamento_Bebida1`
    FOREIGN KEY (`idOrçamento`)
    REFERENCES `mydb`.`Bebida` (`idBebida`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orcamento_Comida1`
    FOREIGN KEY (`idOrçamento`)
    REFERENCES `mydb`.`Comida` (`idComida`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IntensOrcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IntensOrcamento` (
  `idItem` INT NOT NULL,
  `tipoItem` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `precoUnitario` DECIMAL(10,2) NULL,
  `preco_total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idItem`),
  CONSTRAINT `idOrcamento`
    FOREIGN KEY (`idItem`)
    REFERENCES `mydb`.`Orcamento` (`idOrçamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
